#+TITLE:Followup
#+AUTHOR:Marcus Birkenkrahe
#+SUBTITLE:Followup for CSC330 Database Theory & Applications Spring 2022
#+STARTUP:overview hideblocks
#+OPTIONS: toc:nil num:nil ^:nil
* What is this?

  Instead of bugging you with emails, I opt to summarize my course
  observations regarding content, process, in this file. These often
  contain additional links, articles, and musings.

  I usually update it after each class - it also contains the homework
  (if any). The first point of call for any questions should be the
  FAQ. There are two FAQs - a [[https://github.com/birkenkrahe/org/blob/master/FAQ.org#frequently-asked-questions][general one]] (for all my courses), and a
  [[https://github.com/birkenkrahe/cc100/blob/main/FAQ.org][FAQ for CSC 100]].

* Week 1 - first session (Wed 12-Jan-2022)

  See also: [[https://drive.google.com/file/d/1etLNSYGIkmw1lFksiOVkAW1HsPGageDC/view?usp=sharing][Google Meet chat]]

** Homework (until Tuesday, 18 Jan, 11:59 PM)

   | IF YOU DID NOT COMPLETE DSC101                  | IF YOU COMPLETED DSC101            |
   |-------------------------------------------------+------------------------------------|
   | Complete "Datascience for everyone" on DataCamp |                                    |
   | Complete "Introduction to R" on DataCamp        |                                    |
   | Pass the Entry Quiz (Schoology) > 50%           | Complete the Entry quiz (Schoology) |

** Stuff

*** Books
    
   
*** Regular expressions

    Important for efficient text mining and string manipulation,
    e.g. when doing data science on the command line, [[https://en.wikipedia.org/wiki/Regular_expression][regexp]] are
    search patterns. Here is a [[https://regexone.com/][complete, free, online tutorial]]
    (RegexOne, 2021), and here is a [[https://nostarch.com/download/automate2e_SampleCh7.pdf][free book chapter]] explaining
    regexp as part of automating stuff with Python (Sweigart, 2019).
    
*** 

* References

  RegexOne (2021). Lesson 1: An Introduction, and the ABCs
  [tutorial]. [[https://regexone.com/][URL: regexone.com]].

  Sweigart (2019). Automating the boring stuff with
  Python. NoStarch. [[https://nostarch.com/automatestuff2][URL: nostarch.com/automatestuff2]].
