#+TITLE:Introduction to Advanced Data Science
#+AUTHOR:Marcus Birkenkrahe
#+SUBTITLE: DSC 205 @ Lyon College Spring 2022
#+OPTIONS: toc:nil
* What's in this repo?

  * Repository for DSC 205 - Introduction to Advanced Data Science
  * Emacs Org-mode files are rendered as Markdown.
  * For a TOC, open the bullet point list menu

** [[https://github.com/birkenkrahe/dsc101/blob/main/schedule.md][Schedule]] of the course (up to date)
** [[https://github.com/birkenkrahe/dsc101/blob/main/agenda.md][Agenda]] for every session
** [[https://github.com/birkenkrahe/dsc101/blob/main/diary.md][Course diary]] for further reading
** [[https://github.com/birkenkrahe/dsc101/discussions][Discussion forums]] for assignments
** [[https://github.com/birkenkrahe/dsc101/blob/main/FAQ.md][Frequently Asked Questions (FAQ)]]
** [[https://github.com/birkenkrahe/dsc101/blob/main/syllabus.md][Syllabus]] for a course overview

** History

   First offered @Lyon: Spring 2022 (Undergrad). To be offered:
   Spring 2024, 2026, 2028.

** Credo

   | "Getting it right is crucial when people's lives are affected." -Jonathan Steinhart |

   
   #+begin_quote
   "It is clear from the rising interest in statistics over calculus
   that 'data wrangling' is a growing field. But what happens when
   people just feed giant piles of data into fancy programs that those
   same people don't intimately understand? One possibility is that
   they generate interesting-looking but meaningless or incorrect
   results. For example, a recent study ("Gene Name Errors Are
   Widespread in the Scientific Literature" by Mark Ziemann, Yotam
   Eren, and Assam El-Osta) showed that one-fifth of published
   genetics papers have errors due to improper spreadsheet
   usage. Getting it right is crucial when people's lives are
   affected." .(Steinhart, 2019).
   #+end_quote

   Steinhart (2019). The Secret Life of Programs. NoStarch Press. [[https://nostarch.com/foundationsofcomp][URL:
   nostarch.com.]]
